local localStep = 0
function onCreate()
    makeLuaSprite("bg", 'stages/object/sky', 0, 0)
    scaleObject('bg', 0.9, 0.9, true)
    screenCenter("bg", 'xy')
    setProperty('bg.y', getProperty('bg.y') - 200)
    setProperty('bg.x', getProperty('bg.x') + 70)
    addLuaSprite('bg')

    makeLuaSprite("ground", 'stages/object/ground', -650, 200)
    scaleObject('ground', 0.9, 0.9, true)
    addLuaSprite('ground')

    makeLuaSprite("backTree", 'stages/object/back_trees', 0, 0)
    scaleObject('backTree', 0.9, 0.9, true)
    screenCenter("backTree", 'xy')
    setProperty('backTree.y', getProperty('backTree.y') - 100)
    addLuaSprite('backTree')
    
    makeLuaSprite("midTree", 'stages/object/middle_trees', 0, 0)
    scaleObject('midTree', 0.9, 0.9, true)
    screenCenter("midTree", 'xy')
    addLuaSprite('midTree')

    makeLuaSprite("frontTree", 'stages/object/front_trees', 0, 0)
    scaleObject('frontTree', 0.9, 0.9, true)
    screenCenter("frontTree", 'xy')
    addLuaSprite('frontTree')

    makeLuaSprite("cereal killer", 'stages/object/michael-myers', 0, 0)
    scaleObject('cereal killer', 1, 1, true)
    screenCenter("cereal killer", 'xy')
    setProperty('cereal killer.x', getProperty('cereal killer.x') - 60)
    setProperty('cereal killer.y', getProperty('cereal killer.y') + 40)
    addLuaSprite('cereal killer')

    makeLuaSprite("mLight", 'stages/object/moonlight', 0, 0)
    scaleObject('mLight', 0.9, 0.9, true)
    screenCenter("mLight", 'xy')
    setProperty('mLight.alpha', 0.6)
    setProperty('mLight.x', getProperty('mLight.x') - 10)
    setProperty('mLight.y', getProperty('mLight.y') - 100)
    addLuaSprite('mLight', true)
    --setBlendMode("mLight", 'difference')

    makeLuaSprite("bLight", 'stages/object/blue_light', 0, 0)
    scaleObject('bLight', 0.8, 0.8, true)
    screenCenter("bLight", 'xy')
    setProperty('bLight.alpha', 0.4)
    --setProperty('bLight.x', getProperty('mLight.x') - 10)
    setProperty('bLight.y', getProperty('bLight.y') - 200)
    addLuaSprite('bLight', true)
    setBlendMode("bLight", 'erase')

    makeLuaSprite("fog", 'stages/object/fog_left', 0, 0)
    scaleObject('fog', 0.9, 0.9, true)
    screenCenter("fog", 'xy')
    setProperty('fog.y', getProperty('fog.y') + 200)
    setProperty('fog.x', getProperty('fog.x') - 900)
    addLuaSprite('fog', true)
    setBlendMode("fog", 'add')

    makeLuaSprite("also fog", 'stages/object/fog_right', 0, 0)
    scaleObject('also fog', 0.9, 0.9, true)
    screenCenter("also fog", 'xy')
    setProperty('also fog.y', getProperty('also fog.y') + 300)
    setProperty('also fog.x', getProperty('also fog.x') + 900)
    addLuaSprite('also fog', true)
    setBlendMode("also fog", 'add')
end

function onCreatePost()
    setProperty('dadGroup.visible', false)
end